function searchSumAnswers(q){if(!jQuery("#poisk_form textarea").val().trim()){jQuery("#sum_answers").html("Результатов (0)");jQuery("#ans_not_found").fadeOut();return}
jQuery.getJSON("/api/search.php",{q:q,type:"getSumAnswers"},function(data){if(data.status=='OK'&&data.sum>0&&q==jQuery("#poisk_form textarea").val().trim()){jQuery("#sum_answers").html("Результатов ("+data.sum+")");jQuery("#ans_not_found").fadeOut()}else if(q==jQuery("#poisk_form textarea").val().trim()){jQuery("#sum_answers").html("Результатов (0)");jQuery("#ans_not_found").fadeIn(100)}})}
var tID;jQuery("#poisk_form textarea").on("input onkeyup",function(e){this.value?jQuery("#resetSumAnswers").show():jQuery("#resetSumAnswers").hide();clearTimeout(tID);tID=setTimeout(function(){searchSumAnswers(jQuery("#poisk_form textarea").val().trim())},300)});jQuery("#resetSumAnswers").click(function(){jQuery("#poisk_form textarea").val("");jQuery("#sum_answers").html("Результатов (0)");jQuery("#ans_not_found").fadeOut();$(this).hide()});jQuery("#ans_not_found a, .ask-banner__comp, .ask-banner__mob").click(function(e){jQuery("#fly_search").hide();if(this.parentNode.id=="ans_not_found"){jQuery("#fly_ask textarea").val(jQuery("#poisk_form textarea").val())}
jQuery("#fly_ask").fadeIn(200);jQuery("#ask-captcha").show();jQuery("#ask-captcha2").hide();if(jQuery("#ask-captcha div").length){return!1}
var s=document.createElement("script");s.src="https://www.google.com/recaptcha/api.js?onload=onloadCaptchaCallback&render=explicit&hl=ru";document.head.appendChild(s);window.onloadCaptchaCallback=function(){grecaptcha.render('ask-captcha',{'sitekey':document.getElementById('ask-captcha').dataset.sitekey,'callback':verifyCallback})}
window.verifyCallback=function(token){jQuery.post("/api/que_to_mail.php?"+Math.random(),{token:token,name:jQuery("#fly_ask input[name=name]").val(),email:jQuery("#fly_ask input[name=email]").val(),question:jQuery("#fly_ask textarea[name=question]").val().trim(),subject:jQuery("#fly_ask select").val()},function(data){if(data=='OK'){jQuery("#fly_recaptcha").hide();jQuery("#fly_ask-succes").fadeIn(200);jQuery("#fly_ask input, #fly_ask textarea").val("");$("#fly_ask input[type=file]").next().children().html("Добавить фото")}else{grecaptcha.reset()}})}
return!1});jQuery("#fly_ask input[type=file]").change(function(){$(this).next().children().html(this.files.length?this.files.length+" фото добавлено":"Добавить фото")});function validateEmail(email){var re=/^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;return(re.test(email)&&email.length<=60)}
function validateUsername(username){return(username.length>=3&&username.length<=30)}
jQuery("#ask_send").click(function(){jQuery("#fly_ask input").removeClass("error");jQuery("#fly_ask .fly__input-error").hide();let err=0;if(!validateUsername(jQuery("#fly_ask input[name=name]").val())){jQuery("#fly_ask input[name=name]").addClass("error");err=1}
if(!validateEmail(jQuery("#fly_ask input[name=email]").val())){jQuery("#fly_ask input[name=email]").addClass("error");err=1}
if(!xhr_validate(jQuery("#fly_ask textarea[name=question]").val())){jQuery("#fly_ask .fly__input-error").fadeIn(200);err=1}
if(jQuery("#fly_ask select option:first").is(":selected")){!jQuery("#fly_ask select").data("border")&&jQuery("#fly_ask select").data("border",jQuery("#fly_ask select").css("border-color"));jQuery("#fly_ask select").css({borderColor:"red"});err=1}
if(!err){grecaptcha.reset();jQuery("#fly_ask").hide();jQuery("#fly_recaptcha").fadeIn(200)}
return!1});jQuery("#fly_ask-succes a").click(function(){jQuery("#fly_ask-succes").hide()});jQuery("#fly_ask select").change(function(){if(jQuery("#fly_ask select option:first").is(":selected")==!1){jQuery("#fly_ask select").css({borderColor:jQuery("#fly_ask select").data("border")})}});jQuery(document).ready(function(){jQuery(".star-rating .star-rating__item").mouseover(function(){if(jQuery(".star-rating").hasClass('star-rating_active')){var i=jQuery(this).attr('data-ratingb');i=parseInt(i);jQuery(".star-rating__live").css('width',i*20+'%')}}).mouseleave(function(){});jQuery(".star-rating").mouseleave(function(){if(jQuery(".star-rating").hasClass('star-rating_active')){jQuery(".star-rating__live").css('width','0')}})});jQuery('.catmenu__more').click(function(){jQuery('.catmenu__hidden').toggle('fast')});jQuery('#question__ansver-button').click(function(){var this_button=$(this);$.ajax({url:'/ajax.php',type:'post',data:'method=other_q&reload=1&ansver=1&id='+$('#cat_id').val(),dataType:'json',cache:!0,beforeSend:function(){$(this_button).text('Загрузка...')},success:function(response){if(response.status=='error'){alert(response.msg)}
if(response.status=='ok'){jQuery('.dop__article-nedav').html(response.msg)}}});return!1});jQuery(document).ready(function(){jQuery.ajaxSetup({cache:!0});wait_f=!1;setTimeout(function(){if(jQuery('#fullscreenBanner').length){wait_f=!0}
if(wait_f){setTimeout(function(){if(jQuery(window).width()>768){if(jQuery('.banner-top-comp').length&&jQuery('#adfox_154357846978093210').length){window.Ya.adfoxCode.createAdaptive({ownerId:220463,containerId:'adfox_154357846978093210',params:{p1:'ccswu',p2:'fqhi',}},['desktop','tablet','phone'],{tabletWidth:1000,phoneWidth:768,isAutoReloads:!1})}
if(jQuery('.banner-mob').length&&jQuery('#adfox_154357846454811185').length){window.Ya.adfoxCode.createAdaptive({ownerId:220463,containerId:'adfox_154357846454811185',params:{p1:'ccsww',p2:'fqhh',}},['desktop'],{tabletWidth:1000,phoneWidth:768,isAutoReloads:!1})}
if($('#is_question').length){window.Ya.adfoxCode.createAdaptive({ownerId:220463,containerId:'adfox_154357358313274126',params:{p1:'ccswx',p2:'fqil',}},['desktop'],{tabletWidth:1000,phoneWidth:768,isAutoReloads:!1})}}},500)}},0)});jQuery(document).ready(function(){jQuery('ul li:first-child').addClass('first');jQuery('ul li:last-child').addClass('last');jQuery('.category').click(function(){jQuery('.category__items').toggle('fast')});jQuery('.header .search, .right__banner-search').click(function(){jQuery('#fly_search').fadeIn('fast');jQuery('body').addClass('smooth')});jQuery('#fly_mozg .fly__but a').click(function(){jQuery('#fly_mozg').fadeOut('fast');jQuery('#fly_mozg2').fadeOut('fast')});jQuery('#fly_mozg .fly__shadow2').click(function(){jQuery('#fly_mozg').fadeOut('fast')});jQuery('#fly_mozg a.loadUrl').click(function(){jQuery('#fly_mozg3').fadeIn('fast')});jQuery('.fly__shadow3, .fly_close3').click(function(){jQuery('#fly_mozg3').fadeOut('fast')});jQuery('#fly_mozg2 .fly__body').click(function(){jQuery('#fly_mozg').fadeIn('fast');return!1});jQuery('.fly__form2-text.fly__form2-text-b a').click(function(){jQuery('#fly_mozg4').fadeIn('fast');return!1});jQuery('.fy__close4, .fly__shadow4').click(function(){jQuery('#fly_mozg4').fadeOut('fast');return!1});jQuery('.mozgsearch').on('keyup',function(){var text='/megamozg#'+jQuery('.mozgsearch').val();jQuery('.mozgsearchurl').attr('href',text);jQuery('.mozgsearchurl').prop('href',text)});jQuery('.fly__shadow, .fly__but .close, .fy__close').click(function(){jQuery('.fly__form').fadeOut('fast');jQuery('.fly__form2').fadeOut('fast');jQuery('body').removeClass('smooth');return!1});var more=10;jQuery("body").on("click",".question__more a",function(){var url_reload=jQuery(this).attr('href');jQuery(this).attr('href',parseInt(url_reload)+4);var url='/ajax.php';if(jQuery('#cat_type').val()=='book'){url='/ajax_book.php';jQuery(this).attr('href',parseInt(url_reload)+8)}else{jQuery(this).attr('href',parseInt(url_reload)+4)}
jQuery.ajax({url:url,type:'post',data:'method=more_a&id='+jQuery('#cat_id').val()+'&offset='+more+'&reload='+url_reload,dataType:'json',cache:!0,success:function(response){if(response.status=='error'){alert(response.msg)}
if(response.status=='ok'){more+=10;jQuery(response.msg).insertBefore(jQuery('.question__more'))}}});return!1})});jQuery(document).ready(function($){function getTopOffset(e){var y=300;do{y+=e.offsetTop}while(e=e.offsetParent);return y}
var block=document.getElementById('fixblock');$(document).scroll(function(){var dheyht=$('.content_wr').height()-800;if(window.pageYOffset>dheyht){var newcss='bottom:120px; position: fixed;'}else{var newcss=(topPos<window.pageYOffset+61)?'top:0px; position: fixed;':'position:static;'}
block.setAttribute('style',newcss)});if(null!=block){var topPos=getTopOffset(block);window.onscroll=function(){var dheyht=$('.content_wr').height()-800;if(window.pageYOffset>dheyht){var newcss='bottom:120px; position: fixed;'}else{var newcss=(topPos<window.pageYOffset+61)?'top:0px; position: fixed;':'position:static;'}
block.setAttribute('style',newcss)}}});jQuery(document).ready(function($){var loaderpage=3;function loaderpagef(){loaderpage--;if(loaderpage>0){setTimeout(loaderpagef,1000)}else{jQuery('body').addClass('loading')}}
loaderpagef();var loaderpage2=7;function loaderpagef2(){loaderpage2--;if(loaderpage2>0){setTimeout(loaderpagef2,1000)}else{jQuery('.article_soc_links').fadeIn();jQuery('body').removeClass('loading');jQuery('.question__loading').fadeOut()}}
loaderpagef2()});jQuery(document).ready(function($){jQuery('.fly__form4 .fly__input__value input').click(function(){jQuery(this).removeClass('error')});jQuery('#shov_register-succes').click(function(){var pattern=/^([a-z0-9_\.-])+@[a-z0-9-]+\.([a-z]{2,4}\.)?[a-z]{2,4}$/i;if(pattern.test($('.fly__input__value-mail').val())){}else{jQuery(".fly__input__value-mail").addClass('error');return!1}
if(jQuery('.fly_vopros').is(":visible")){if(jQuery('.fly_vopros textarea').val().length<=30){jQuery('.fly__input-error').fadeIn('fast');return!1}}
jQuery('#fly_login').hide();jQuery('#fly_register').hide();jQuery('#fly_register-succes').fadeIn('fast');return!1});jQuery('#shov_login_text').click(function(){var pattern=/^([a-z0-9_\.-])+@[a-z0-9-]+\.([a-z]{2,4}\.)?[a-z]{2,4}$/i;if(pattern.test($('.fly__input__value-mail2').val())){}else{jQuery(".fly__input__value-mail2").addClass('error');return!1}
jQuery('.fly__input-error').fadeIn('fast');return!1});jQuery('#shov_login, #login_menu, .top-login').click(function(){jQuery('#fly_login').fadeIn();jQuery('#fly_register').hide();jQuery('#fly_register-succes').hide('fast');return!1});jQuery('#shov_register, #register_menu').click(function(){jQuery('#fly_login').hide();jQuery('.fly__input-error').hide();jQuery('.fly_vopros').show();jQuery('#fly_register').fadeIn('fast');jQuery('#fly_register-succes').hide();return!1});jQuery('#shov_send_text').click(function(){var pattern=/^([a-z0-9_\.-])+@[a-z0-9-]+\.([a-z]{2,4}\.)?[a-z]{2,4}$/i;if(pattern.test($('.fly__input__value-mail3').val())){jQuery('.fly__input-error').fadeIn('fast');jQuery('#shov_send_close').show();jQuery('#shov_send_text').hide()}else{jQuery(".fly__input__value-mail3").addClass('error');return!1}
return!1});jQuery('#search_submit_button').click(function(){jQuery('.fly_vopros').hide();jQuery('#fly_login').hide();jQuery('.fly__input-error').hide();jQuery('#fly_register').fadeIn('fast');jQuery('#fly_register-succes').hide();return!1});jQuery('#shov_send_close').click(function(){jQuery('#fly_email-send').fadeOut('fast')});jQuery('.fly__input-remember').click(function(){jQuery('#fly_email-send').fadeIn('fast');jQuery('#fly_login').hide();jQuery('.fly__input-error').hide();jQuery('#fly_register').hide('fast');jQuery('#fly_register-succes').hide()})});function xhr_validate(data){let xhr=jQuery.ajax({async:!1,url:"/api/que_to_mail.php?"+Math.random(),type:"POST",data:{validate:data},cache:!1});return~~xhr.responseText}
function view_question(id){jQuery.getScript("/api/view.php?id="+id+"&"+Math.random())}